In [1]:
import pandas as pd

In [4]:
d1=pd.read_excel(r"C:\Users\Hp\Desktop\python\Global_Superstore.xlsx",sheet_name='Orders')
d1

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High

In [5]:
d2=pd.read_excel(r"C:\Users\Hp\Desktop\python\Global_Superstore.xlsx",sheet_name='Return')
d2

                      Order_ID Returned           Region
0     CA-2012-SA20830140-41210      Yes       Central US
1     IN-2012-PB19210127-41259      Yes     Eastern Asia
2     CA-2012-SC20095140-41174      Yes       Central US
3       IN-2015-JH158207-42140      Yes          Oceania
4       IN-2014-LC168857-41747      Yes          Oceania
...                        ...      ...              ...
1074   IN-2014-DA1345058-41769      Yes    Southern Asia
1075  US-2013-HG14845140-41530      Yes       Eastern US
1076   US-2013-SJ2021582-41543      Yes  Central America
1077  CA-2015-EB13870140-42269      Yes       Eastern US
1078    EG-2014-PM894038-41846      Yes     North Africa

[1079 rows x 3 columns]

In [11]:
pd.merge(d1,d2,on='Order_ID',how='inner')

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Returned,Region_y
0,30191,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Tables,"Lesro Conference Table, with Bottom Storage",1715.160,2,0.0,720.3600,725.570,Critical,Yes,Eastern Asia
1,30190,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Bookcases,"Safco Classic Bookcase, Pine",2197.500,5,0.0,153.7500,627.270,Critical,Yes,Eastern Asia
2,30187,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Tables,"Lesro Round Table, with Bottom Storage",1356.030,3,0.0,311.8500,458.970,Critical,Yes,Eastern Asia
3,30193,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Chairs,"Office Star Swivel Stool, Adjustable",882.150,5,0.0,114.6000,203.920,Critical,Yes,Eastern Asia
4,30189,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Machines,"Okidata Calculator, Red",148.320,3,0.0,68.2200,25.480,Critical,Yes,Eastern Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,35040,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,Binders,"Square Ring Data Binders, Rigid 75 Pt. Covers,...",49.536,3,0.2,17.3376,2.670,Medium,Yes,Eastern US
2216,35038,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,Envelopes,"#10 Gummed Flap White Envelopes, 100/Box",16.520,4,0.0,7.5992,1.690,Medium,Yes,Eastern US
2217,25,US-2013-SJ2021582-41543,2013-09-26,2013-09-29,First Class,SJ-2021582,Sarah Jordon,Consumer,NaN,Hermosillo,...,Furnishings,"Deflect-O Clock, Black",181.116,9,0.4,-75.5640,1.085,Medium,Yes,Central America
2218,36974,CA-2012-ZC21910140-41271,2012-12-28,2013-01-04,Standard Class,ZC-219101402,Zuschuss Carroll,Consumer,60610.0,Chicago,...,Furnishings,Tenex Chairmats For Use with Hard Floors,38.976,3,0.6,-50.6688,5.290,Low,Yes,Central US
2219,41315,EG-2014-PM894038-41846,2014-07-26,2014-07-30,Standard Class,PM-894038,Paul MacIntyre,Consumer,NaN,Alexandria,...,Art,"Sanford Pencil Sharpener, Fluorescent",25.830,1,0.0,9.0300,1.050,Medium,Yes,North Africa

In [12]:
pd.merge(d1,d2,on='Order_ID',how='outer')

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Returned,Region_y
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,NaN,NaN
1,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.0,54.7136,25.270,High,NaN,NaN
2,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,NaN,NaN
3,26339,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,Copiers,"Brother Fax and Copier, Laser",344.682,2,0.1,34.4220,65.350,Critical,NaN,NaN
4,26340,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,Storage,"Rogers Folders, Wire Frame",133.920,5,0.1,-6.0300,41.640,Critical,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,6039,MX-2015-HG1502518-42164,2015-06-09,2015-06-11,First Class,HG-1502518,Hunter Glantz,Consumer,NaN,Bragança Paulista,...,Paper,"Green Bar Message Books, Multicolor",84.000,5,0.0,9.2000,1.019,High,NaN,NaN
51286,24175,IN-2015-DB132707-42221,2015-08-05,2015-08-10,Standard Class,DB-132707,Deborah Brumfield,Home Office,NaN,Townsville,...,Binders,"Avery Binder, Economy",58.050,5,0.1,19.9500,1.010,Medium,NaN,NaN
51287,24105,IN-2015-KH1633058-42154,2015-05-30,2015-05-30,Same Day,KH-1633058,Katharine Harms,Corporate,NaN,Lucknow,...,Paper,"Eaton Parchment Paper, Premium",26.940,2,0.0,1.8600,1.010,High,NaN,NaN
51288,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,NaN,NaN
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,NaN,NaN

In [13]:
pd.merge(d1,d2,on='Order_ID',how='left')

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Returned,Region_y
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,NaN,NaN
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,NaN,NaN
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,NaN,NaN
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,NaN,NaN
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium,NaN,NaN
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,NaN,NaN
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High,NaN,NaN
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium,NaN,NaN
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,NaN,NaN

In [14]:
pd.merge(d1,d2,on='Order_ID',how='right')

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Returned,Region_y
0,31784,CA-2012-SA20830140-41210,2012-10-28,2012-10-30,First Class,SA-208301402,Sue Ann Reed,Consumer,60610.0,Chicago,...,Phones,Apple iPhone 5S,2735.952,6,0.2,341.9940,752.510,High,Yes,Central US
1,30191,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Tables,"Lesro Conference Table, with Bottom Storage",1715.160,2,0.0,720.3600,725.570,Critical,Yes,Eastern Asia
2,30190,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Bookcases,"Safco Classic Bookcase, Pine",2197.500,5,0.0,153.7500,627.270,Critical,Yes,Eastern Asia
3,30187,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Tables,"Lesro Round Table, with Bottom Storage",1356.030,3,0.0,311.8500,458.970,Critical,Yes,Eastern Asia
4,30193,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,Chairs,"Office Star Swivel Stool, Adjustable",882.150,5,0.0,114.6000,203.920,Critical,Yes,Eastern Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,28736,IN-2014-DA1345058-41769,2014-05-10,2014-05-15,Standard Class,DA-1345058,Dianna Arnett,Home Office,NaN,Thane,...,Binders,"Avery Binder Covers, Durable",12.570,1,0.0,0.2400,1.100,Medium,Yes,Southern Asia
2216,37649,US-2013-HG14845140-41530,2013-09-13,2013-09-19,Standard Class,HG-148451406,Harry Greene,Consumer,19120.0,Philadelphia,...,Binders,"Fellowes Twister Kit, Gray/Clear, 3/pkg",2.412,1,0.7,-2.0100,1.100,Medium,Yes,Eastern US
2217,25,US-2013-SJ2021582-41543,2013-09-26,2013-09-29,First Class,SJ-2021582,Sarah Jordon,Consumer,NaN,Hermosillo,...,Furnishings,"Deflect-O Clock, Black",181.116,9,0.4,-75.5640,1.085,Medium,Yes,Central America
2218,36053,CA-2015-EB13870140-42269,2015-09-22,2015-09-26,Standard Class,EB-138701406,Emily Burns,Consumer,19143.0,Philadelphia,...,Binders,Insertable Tab Indexes For Data Binders,1.908,2,0.7,-1.5264,1.060,Medium,Yes,Eastern US
2219,41315,EG-2014-PM894038-41846,2014-07-26,2014-07-30,Standard Class,PM-894038,Paul MacIntyre,Consumer,NaN,Alexandria,...,Art,"Sanford Pencil Sharpener, Fluorescent",25.830,1,0.0,9.0300,1.050,Medium,Yes,North Africa

In [25]:
d1.iloc[1:11,1:6]

,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID
1,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107
2,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307
3,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548
4,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111
5,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557
6,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092
7,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592
8,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402
9,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404
10,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404

In [28]:
d1.loc[1:10,'Order_ID':'Customer ID']

,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID
1,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107
2,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307
3,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548
4,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111
5,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557
6,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092
7,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592
8,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402
9,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404
10,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404

In [24]:
d1.head(10)

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.0,54.7136,25.27,High
9,36258,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,FUR-CH-4421,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,11.13,High

In [31]:
d1.loc[d1.Profit>0,:]

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.350,Critical
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.770,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High

In [33]:
d1.rename(columns={'Sales':'Revenue'})

,Row ID,Order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product_ID,Category,Sub_Category,Product_Name,Revenue,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High

In [34]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order_ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product_ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub_Category    51290 non-null  object
 17  Product_Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping_Cost   51290 non-null  float64
 23  Order_Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [39]:
change_data={'Row ID':str,'Quantity':str}
d1=d1.astype(change_data)

In [40]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  object
 1   Order_ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product_ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub_Category    51290 non-null  object
 17  Product_Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  object
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping_Cost   51290 non-null  float64
 23  Order_Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), object(17)
memory usage: 9.4+ MB